/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "led.h"

int main(void)
{
	led_init(LED_GREEN);
	led_init(LED_ORANGE);
	led_init(LED_RED);

	while(1){
		led_on(LED_GREEN);
		DelayMs(5000);
		led_off(LED_GREEN);

		led_on(LED_ORANGE);
		DelayMs(5000);
		led_off(LED_ORANGE);

		led_on(LED_RED);
		DelayMs(5000);
		led_off(LED_RED);


	}
}












